server:
  port: 8082

spring:
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialet: org.hibernate.dialect.MySQLSDialec
  datasource:
    url: jdbc:mysql://localhost:3306/users?serverTimezone=UTC&useSSL=false
    username: root
    password: Ferchu77.  
    driver-class-name: com.mysql.cj.jdbc.Driver